---
name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          echo "${{github.event_name}}"
          echo "${{github.event}}"
